<?php require VIEWS_PATH . 'includes/header.phtml';?>

<main role="main" class="container">
  <div class="jumbotron">
    <h1>Pagina nao encontrada!!!</h1>
    <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
  </div>
</main>

 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>