<?php require VIEWS_PATH . 'includes/header.phtml';?>

<main role="main" class="container">
  <div class="jumbotron">
    <h1>CONTATOS</h1>
    <ul>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    <li>LINK DE EMAIL</li>
    </ul>
  </div>
</main>

 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>